import type { User, Chat, ChatMessage, Mentor } from './types';
export const MOCK_USERS: User[] = [
  { id: 'u1', name: 'User A', email: 'usera@example.com', bio: 'Bio for User A', passwordHash: 'password123', isMentor: true },
  { id: 'u2', name: 'User B', email: 'userb@example.com', bio: 'Bio for User B', passwordHash: 'password456', isMentor: true }
];
export const MOCK_CHATS: Chat[] = [
  { id: 'c1', title: 'General' },
];
export const MOCK_CHAT_MESSAGES: ChatMessage[] = [
  { id: 'm1', chatId: 'c1', userId: 'u1', text: 'Hello', ts: Date.now() },
];
export const MOCK_MENTORS: Mentor[] = [
    {
        id: 'mentor-1',
        name: 'Sarah Chen',
        title: 'Principal Engineer',
        company: 'Innovate Inc.',
        specialties: ['Frontend', 'React', 'TypeScript', 'Web Performance'],
        bio: 'Sarah is a passionate frontend developer with over 10 years of experience building scalable and beautiful web applications. She loves mentoring junior developers and helping them grow their careers.',
        imageUrl: 'https://i.pravatar.cc/300?u=mentor-1',
    },
    {
        id: 'mentor-2',
        name: 'Michael Rodriguez',
        title: 'Backend Architect',
        company: 'DataStream Solutions',
        specialties: ['Node.js', 'Microservices', 'AWS', 'System Design'],
        bio: 'Michael specializes in designing robust and scalable backend systems. He has a deep understanding of cloud infrastructure and enjoys tackling complex architectural challenges.',
        imageUrl: 'https://i.pravatar.cc/300?u=mentor-2',
    },
    {
        id: 'mentor-3',
        name: 'Emily White',
        title: 'Product Manager',
        company: 'NextGen Products',
        specialties: ['Product Strategy', 'User Research', 'Agile', 'Roadmapping'],
        bio: 'Emily is a user-centric product manager who excels at turning ideas into successful products. She is skilled in market analysis, user feedback, and leading cross-functional teams.',
        imageUrl: 'https://i.pravatar.cc/300?u=mentor-3',
    },
    {
        id: 'mentor-4',
        name: 'David Lee',
        title: 'UX/UI Design Lead',
        company: 'Creative Minds Studio',
        specialties: ['User Experience', 'Interaction Design', 'Figma', 'Design Systems'],
        bio: 'David has a keen eye for detail and a passion for creating intuitive and delightful user interfaces. He leads a team of designers in crafting pixel-perfect experiences.',
        imageUrl: 'https://i.pravatar.cc/300?u=mentor-4',
    },
    {
        id: 'mentor-5',
        name: 'Jessica Taylor',
        title: 'Data Scientist',
        company: 'Quantum Analytics',
        specialties: ['Machine Learning', 'Python', 'Data Visualization', 'Statistics'],
        bio: 'Jessica is a data scientist who loves to find stories in data. She has experience in building predictive models and deriving actionable insights from complex datasets.',
        imageUrl: 'https://i.pravatar.cc/300?u=mentor-5',
    },
    {
        id: 'mentor-6',
        name: 'Chris Martinez',
        title: 'DevOps Engineer',
        company: 'CloudDeploy',
        specialties: ['CI/CD', 'Kubernetes', 'Terraform', 'Site Reliability'],
        bio: 'Chris is an expert in automating infrastructure and streamlining development pipelines. He is passionate about building resilient and efficient systems.',
        imageUrl: 'https://i.pravatar.cc/300?u=mentor-6',
    },
    {
        id: 'mentor-7',
        name: 'Amanda Brown',
        title: 'Marketing Director',
        company: 'GrowthLeap',
        specialties: ['Digital Marketing', 'SEO', 'Content Strategy', 'Brand Building'],
        bio: 'Amanda is a results-driven marketing leader with a track record of growing brands and acquiring users through innovative digital strategies.',
        imageUrl: 'https://i.pravatar.cc/300?u=mentor-7',
    },
    {
        id: 'mentor-8',
        name: 'Kevin Wilson',
        title: 'Mobile Developer',
        company: 'Appify',
        specialties: ['iOS', 'Swift', 'Android', 'Kotlin', 'React Native'],
        bio: 'Kevin builds beautiful and performant mobile applications for both iOS and Android platforms. He is proficient in native and cross-platform development.',
        imageUrl: 'https://i.pravatar.cc/300?u=mentor-8',
    },
    {
        id: 'mentor-9',
        name: 'Laura Garcia',
        title: 'Cybersecurity Analyst',
        company: 'SecureNet',
        specialties: ['Network Security', 'Penetration Testing', 'Incident Response'],
        bio: 'Laura is dedicated to protecting digital assets from threats. She has a strong background in identifying vulnerabilities and securing systems.',
        imageUrl: 'https://i.pravatar.cc/300?u=mentor-9',
    },
    {
        id: 'mentor-10',
        name: 'James Johnson',
        title: 'Venture Capitalist',
        company: 'Future Ventures',
        specialties: ['Startups', 'Fundraising', 'Business Strategy', 'Pitching'],
        bio: 'James helps early-stage startups secure funding and develop winning business strategies. He has a deep network in the tech and investment communities.',
        imageUrl: 'https://i.pravatar.cc/300?u=mentor-10',
    },
    {
        id: 'mentor-11',
        name: 'Olivia Davis',
        title: 'AI Researcher',
        company: 'Cognitive AI Labs',
        specialties: ['Natural Language Processing', 'Deep Learning', 'PyTorch'],
        bio: 'Olivia is at the forefront of AI research, working on cutting-edge models for language understanding and generation.',
        imageUrl: 'https://i.pravatar.cc/300?u=mentor-11',
    },
    {
        id: 'mentor-12',
        name: 'Daniel Kim',
        title: 'Founder & CEO',
        company: 'ConnectSphere',
        specialties: ['Entrepreneurship', 'Leadership', 'Product-Market Fit'],
        bio: 'Daniel is a serial entrepreneur who successfully built and exited two tech companies. He now mentors aspiring founders on their journey.',
        imageUrl: 'https://i.pravatar.cc/300?u=mentor-12',
    },
];